const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const elements = Object.fromEntries(['editionCard','nieuws','secondaryArticles','regionArticles','sectorArticles'].map(id => [id,{innerHTML:''}]));
const context = vm.createContext({console, Intl, URLSearchParams, document:{getElementById:id=>elements[id]}, navigator:{}, fetch:async()=>{throw Error('offline');}});
const code = fs.readFileSync('app.js','utf8').replace('initEdition();','').replace('initSearch();','');
vm.runInContext(code,context);
const editions = JSON.parse(fs.readFileSync('data/editions.json'));
const articles = JSON.parse(fs.readFileSync('data/articles.json'));
context.editions = editions.reverse(); context.articles = articles;
vm.runInContext('var result = selectEdition(editions,articles); renderHomepage(result.selected);',context);
const latest = [...editions].sort((a,b)=>b.date.localeCompare(a.date))[0];
assert.equal(context.result.edition.date,latest.date);
assert.deepEqual(Array.from(context.result.selected,a=>a.id),latest.articleIds);
for (const article of context.result.selected.slice(0,2)) assert.ok(elements.nieuws.innerHTML.includes(encodeURIComponent(article.id)));
assert.ok(!elements.nieuws.innerHTML.includes('id=olie-gas-ontwikkeling'));
vm.runInContext(`renderHomepage([{id:'safe',section:'Guyana',title:'<script>bad</script>',lead:'x'}])`,context);
assert.ok(elements.nieuws.innerHTML.includes('&lt;script&gt;'));
assert.equal(elements.secondaryArticles.innerHTML,'');
assert.ok(elements.regionArticles.innerHTML.includes('id=safe'));
vm.runInContext('renderHomepage([])',context);
assert.ok(elements.nieuws.innerHTML.includes('nog geen artikelen'));
assert.throws(()=>vm.runInContext('selectEdition([],[])',context));
vm.runInContext("var missing = selectEdition([{date:'2026-09-09',articleIds:['absent','safe','safe']}],[{id:'safe'}]);",context);
assert.equal(context.missing.selected.length,1);
(async()=>{await vm.runInContext('initEdition()',context); assert.ok(elements.editionCard.innerHTML.includes('niet worden geladen')); console.log('Homepage tests passed: latest edition, ID ordering, rendering, missing/duplicate IDs, empty data, escaping and fetch failure.');})();
